#!/usr/bin/env bash
[[ "$1" == --version ]] && { echo "multiqc, version 1.28"; exit 0; }
while (( $# )); do case "$1" in -o) o="$2"; shift 2 ;; -n) n="$2"; shift 2 ;; *) shift ;; esac; done
echo "<html>stub</html>" > "$o/$n"
